### ISSUE TITLE
Build on ARM (raspberry pi)

### ISSUE THREAD

**Issue by zeldor** [mlavin/sickmuse#19]
I've tried to build sickmuse on a respberry pi with Debian 8 and run in the following issue:
I there any explanation fix for it - see error in the attachment:
[status.txt](https://github.com/mlavin/sickmuse/files/749106/status.txt)

Thank you in advice
BR

**Comment by mlavin** [comment]
This looks like a problem in installing the [`python-rrdtool`][0] requirement. As they noted you need rrdtool and its development headers installed to compile it. I have no experience doing that myself on a Raspberry Pi.

[0]: https://github.com/commx/python-rrdtool

**Comment by zeldor** [comment]
Mark, thank you for your help! indeed, librrd-dev was not installed.
